global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'nifi-jmx'
    static_configs:
      - targets: ['nifi-n:9404']

  - job_name: 'minio'
    metrics_path: /minio/v2/metrics/cluster
    static_configs:
      - targets: ['minio:9000']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres_exporter:9187']

  - job_name: airflow
    scheme: http
    metrics_path: metrics
    static_configs:
      - targets: ['statsd_exporter:9102']
        labels:
          airflow_id: 'airflow'
  
  - job_name: 'node'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'blackbox_sptrans'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://api.olhovivo.sptrans.com.br/v2.1/Posicao
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115

  # - job_name: 'pushgateway'      # opcional p/ batches
  #   static_configs:
  #     - targets: ['pushgateway:9091']